<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.strukovd</groupId>
        <artifactId>fluentway</artifactId>
        <version>0.0.1</version>
    </parent>

    <!-- groupId и version наследуются у родителя -->
    <artifactId>client</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency> <!-- моя зависимость core -->
            <groupId>ru.strukovd</groupId>
            <artifactId>core</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency> <!-- JDBC-драйвер для PostgreSQL. Нужен только во время запуска приложения, не при компиляции (поэтому runtime). -->
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency> <!-- Подключает Spring MVC + встроенный веб-сервер (REST-контроллеры) Tomcat или др. -->
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency> <!-- Подключает Spring Cache абстракцию (@Cacheable, @CacheEvict) -->
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
<!--        <dependency> &lt;!&ndash; Тестовый набор: JUnit 5, AssertJ, Mockito, Spring TestContext. Подключается только в тестах &ndash;&gt;-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-test</artifactId>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.liquibase</groupId>-->
<!--            <artifactId>liquibase-core</artifactId>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>