spring:
  application:
    name: eng

  # Отключение Liquibase
  liquibase:
    enabled: false

  # Профиль для разработки
  profiles:
    active: dev

  # Параметры подключения к базе данных
  datasource:
    url: jdbc:postgresql://localhost:5432/english_db
    username: english
    password: english
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000

  # Параметры JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  # Логирование
#  logging:
#    level:
#      org.hibernate: DEBUG
#      org.springframework.jdbc: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/english_db
    username: english
    password: english
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # В разработке
  server:
    port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/english_db
    username: english
    password: english
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Отключаем автоматическое обновление в продакшн
  server:
    port: 8080



#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
